[versions]
android = "7.4.0-alpha09"
androidxCore = "1.9.0"
kotlin = "1.6.21"
androidxLifecycle = "2.3.1"
androidxActivity = "1.3.1"
androidxCompose = "1.2.0-beta01"
androidxTestExt = "1.1.3"
androidxTestEspresso = "3.4.0"
junit = "4.13.2"

[libraries]
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxComposeUi = { module = "androidx.compose.ui:ui", version.ref = "androidxCompose" }
androidxComposeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidxCompose" }
androidxComposeMaterial = { module = "androidx.compose.material:material", version.ref = "androidxCompose" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidxTestEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidxComposeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxCompose" }
androidxComposeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxCompose" }
androidxComposeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxCompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "android" }
androidLibrary = { id = "com.android.library", version.ref = "android" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint" }

